import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "src/components/navbar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MBST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
      </main>
    </div>
  );
};

export default Home;
