import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ListView from "@modules/list";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MBST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ListView />
    </div>
  );
};

export default Home;
